// Copyright 2026 nosqlbench contributors
// SPDX-License-Identifier: Apache-2.0

//! Throughput benchmarks for slabtastic write and read paths.
//!
//! ## Benchmark groups
//!
//! **Single-threaded:**
//! - `write` — end-to-end write throughput (file create → add_record × N → finish)
//! - `sequential_read` — full-file iteration via `SlabReader::iter`
//! - `random_read` — 10 000 point lookups via `SlabReader::get` with
//!   pseudo-random ordinals spread across the file
//!
//! **Concurrent (multi-threaded):**
//! - `concurrent_random_read` — N threads (2/4/8) each open an independent
//!   `SlabReader` on the same 10 M-record file and perform 10 000 random
//!   `get()` calls with different access patterns. Measures OS page-cache
//!   and file-I/O scaling under read contention.
//! - `concurrent_sequential_read` — N threads (2/4/8) each open their own
//!   `SlabReader` on the same 1 M-record file and call `iter()` to read
//!   every record. Measures sequential bandwidth scaling.
//! - `concurrent_write` — N threads (2/4/8) each write an independent
//!   1 M-record slab file in parallel. Measures aggregate write throughput
//!   when multiple pipelines run simultaneously.
//!
//! Single-threaded read benchmarks use `iter_batched` to open the file in
//! the setup phase (outside the timed region) so that only the actual
//! read operations are measured. Concurrent benchmarks necessarily include
//! per-thread open cost since `SlabReader` is not `Send`.
//!
//! All benchmarks use deterministic 5–25 byte records generated by
//! [`make_record`]. For 100 M+ scale tests see `tests/large_scale.rs`.

use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::thread;

use criterion::{BatchSize, BenchmarkId, Criterion, Throughput, criterion_group, criterion_main};
use slabtastic::{SlabReader, SlabWriter, WriterConfig};
use tempfile::NamedTempFile;

/// Generate a deterministic record of 5–25 bytes based on ordinal.
///
/// The length cycles through 5..=25 (mod 21) so that page packing is
/// exercised with non-uniform record sizes, matching realistic short-text
/// workloads.
fn make_record(ordinal: u64) -> Vec<u8> {
    let len = 5 + (ordinal % 21) as usize;
    let base = format!("{ordinal:0>width$}", width = len);
    base.into_bytes()[..len].to_vec()
}

/// Write a test file with `count` records using default config and return
/// the `NamedTempFile` handle (must be kept alive to prevent deletion)
/// together with the file path.
fn prepare_file(count: u64) -> (NamedTempFile, PathBuf) {
    let tmp = NamedTempFile::new().unwrap();
    let path = tmp.path().to_path_buf();
    let config = WriterConfig::default();
    let mut writer = SlabWriter::new(&path, config).unwrap();
    for i in 0..count {
        writer.add_record(&make_record(i)).unwrap();
    }
    writer.finish().unwrap();
    (tmp, path)
}

// ---------------------------------------------------------------------------
// Single-threaded benchmarks
// ---------------------------------------------------------------------------

/// Measure single-threaded write throughput.
///
/// Each iteration creates a fresh temp file, writes `count` records with
/// default page config (64 KiB preferred), then calls `finish()`. The
/// throughput metric is records per second. File creation is included in
/// the measurement since it is part of the write lifecycle.
fn bench_write(c: &mut Criterion) {
    let mut group = c.benchmark_group("write");
    group.sample_size(10);

    for count in [1_000_000u64, 10_000_000] {
        group.throughput(Throughput::Elements(count));
        group.bench_with_input(
            BenchmarkId::new("records", count),
            &count,
            |b, &count| {
                b.iter(|| {
                    let tmp = NamedTempFile::new().unwrap();
                    let path = tmp.path().to_path_buf();
                    let config = WriterConfig::default();
                    let mut writer = SlabWriter::new(&path, config).unwrap();
                    for i in 0..count {
                        writer.add_record(&make_record(i)).unwrap();
                    }
                    writer.finish().unwrap();
                });
            },
        );
    }
    group.finish();
}

/// Measure single-threaded sequential read throughput via `iter()`.
///
/// The file is opened in the setup phase (outside the timed region) so
/// that only the page-by-page deserialization and record extraction are
/// measured. Uses `iter_batched` with `LargeInput` batch size since each
/// setup allocates a `SlabReader` with its file descriptor and in-memory
/// pages-page index.
fn bench_sequential_read(c: &mut Criterion) {
    let mut group = c.benchmark_group("sequential_read");
    group.sample_size(10);

    for count in [1_000_000u64, 10_000_000] {
        let (_tmp, path) = prepare_file(count);

        group.throughput(Throughput::Elements(count));
        group.bench_with_input(
            BenchmarkId::new("iter", count),
            &count,
            |b, &_count| {
                b.iter_batched(
                    || SlabReader::open(&path).unwrap(),
                    |mut reader| {
                        let records = reader.iter().unwrap();
                        assert!(!records.is_empty());
                    },
                    BatchSize::LargeInput,
                );
            },
        );
    }
    group.finish();
}

/// Measure single-threaded random-access read throughput via `get()`.
///
/// 10 000 pseudo-random ordinals (deterministic, using prime-modular
/// scatter) are looked up against a pre-built file. The file is opened
/// in the setup phase so that only the binary-search index lookup plus
/// single-page deserialization cost is measured per `get()` call.
fn bench_random_read(c: &mut Criterion) {
    let mut group = c.benchmark_group("random_read");
    group.sample_size(10);

    for count in [1_000_000u64, 10_000_000] {
        let (_tmp, path) = prepare_file(count);

        let sample_count = 10_000u64;
        let ordinals: Vec<i64> = (0..sample_count)
            .map(|i| ((i * 7919) % count) as i64)
            .collect();

        group.throughput(Throughput::Elements(sample_count));
        group.bench_with_input(
            BenchmarkId::new("get_10k", count),
            &ordinals,
            |b, ordinals| {
                b.iter_batched(
                    || SlabReader::open(&path).unwrap(),
                    |mut reader| {
                        for &ord in ordinals {
                            let _ = reader.get(ord).unwrap();
                        }
                    },
                    BatchSize::LargeInput,
                );
            },
        );
    }
    group.finish();
}

// ---------------------------------------------------------------------------
// Concurrent benchmarks
// ---------------------------------------------------------------------------

/// Spawn `n_threads` threads, each opening its own `SlabReader` on the
/// same file and performing `reads_per_thread` random `get()` calls.
///
/// Each thread uses a different seed (`thread_index * 6271`) so that
/// threads hit different pages and exercise OS-level read contention
/// rather than all hitting the same cached page.
///
/// Note: `SlabReader` is not `Send`, so each thread must open its own
/// reader. The per-thread open cost is included in the measurement.
fn concurrent_random_reads(path: &Path, n_threads: usize, reads_per_thread: u64, record_count: u64) {
    let path = Arc::new(path.to_path_buf());
    let handles: Vec<_> = (0..n_threads)
        .map(|t| {
            let path = Arc::clone(&path);
            thread::spawn(move || {
                let mut reader = SlabReader::open(&*path).unwrap();
                let seed = (t as u64).wrapping_mul(6271);
                for i in 0..reads_per_thread {
                    let ordinal = ((i.wrapping_mul(7919).wrapping_add(seed)) % record_count) as i64;
                    let _ = reader.get(ordinal).unwrap();
                }
            })
        })
        .collect();
    for h in handles {
        h.join().unwrap();
    }
}

/// Measure concurrent random-access read scaling (2/4/8 threads).
///
/// All threads share the same pre-built 10 M-record file, each with its
/// own `SlabReader` and file descriptor. Throughput is reported as the
/// aggregate number of `get()` calls across all threads per second. Ideal
/// scaling would show near-linear throughput increase, while lower values
/// indicate I/O or page-cache contention.
///
/// Per-thread `SlabReader::open` cost is included since each thread needs
/// its own file descriptor; this is the realistic concurrent access pattern.
fn bench_concurrent_random_read(c: &mut Criterion) {
    let mut group = c.benchmark_group("concurrent_random_read");
    group.sample_size(10);

    let record_count = 10_000_000u64;
    let (_tmp, path) = prepare_file(record_count);
    let reads_per_thread = 10_000u64;

    for n_threads in [2, 4, 8] {
        let total_reads = reads_per_thread * n_threads as u64;
        group.throughput(Throughput::Elements(total_reads));
        group.bench_with_input(
            BenchmarkId::new("threads", n_threads),
            &n_threads,
            |b, &n_threads| {
                b.iter(|| {
                    concurrent_random_reads(&path, n_threads, reads_per_thread, record_count);
                });
            },
        );
    }
    group.finish();
}

/// Spawn `n_threads` threads, each opening its own `SlabReader` and
/// iterating every record via `iter()`.
///
/// Per-thread open cost is included since `SlabReader` is not `Send`.
fn concurrent_sequential_reads(path: &Path, n_threads: usize) {
    let path = Arc::new(path.to_path_buf());
    let handles: Vec<_> = (0..n_threads)
        .map(|_| {
            let path = Arc::clone(&path);
            thread::spawn(move || {
                let mut reader = SlabReader::open(&*path).unwrap();
                let records = reader.iter().unwrap();
                assert!(!records.is_empty());
            })
        })
        .collect();
    for h in handles {
        h.join().unwrap();
    }
}

/// Measure concurrent sequential read scaling (2/4/8 threads).
///
/// All threads share the same pre-built 1 M-record file and each
/// performs a full `iter()`. Throughput is reported as the aggregate
/// record count across all threads per second. This stresses sequential
/// I/O bandwidth when multiple readers compete for the same file.
///
/// Per-thread `SlabReader::open` cost is included since each thread needs
/// its own file descriptor.
fn bench_concurrent_sequential_read(c: &mut Criterion) {
    let mut group = c.benchmark_group("concurrent_sequential_read");
    group.sample_size(10);

    let record_count = 1_000_000u64;
    let (_tmp, path) = prepare_file(record_count);

    for n_threads in [2, 4, 8] {
        let total = record_count * n_threads as u64;
        group.throughput(Throughput::Elements(total));
        group.bench_with_input(
            BenchmarkId::new("threads", n_threads),
            &n_threads,
            |b, &n_threads| {
                b.iter(|| {
                    concurrent_sequential_reads(&path, n_threads);
                });
            },
        );
    }
    group.finish();
}

/// Spawn `n_threads` threads, each writing its own independent slab file
/// with `records_per_thread` records, then closing it.
fn concurrent_writes(n_threads: usize, records_per_thread: u64) {
    let handles: Vec<_> = (0..n_threads)
        .map(|t| {
            thread::spawn(move || {
                let tmp = NamedTempFile::new().unwrap();
                let path = tmp.path().to_path_buf();
                let config = WriterConfig::default();
                let mut writer = SlabWriter::new(&path, config).unwrap();
                let base = t as u64 * records_per_thread;
                for i in 0..records_per_thread {
                    writer.add_record(&make_record(base + i)).unwrap();
                }
                writer.finish().unwrap();
            })
        })
        .collect();
    for h in handles {
        h.join().unwrap();
    }
}

/// Measure concurrent independent-file write scaling (2/4/8 threads).
///
/// Each thread creates and writes its own temp file with 1 M records.
/// Throughput is reported as the aggregate record count across all
/// threads per second. Since each thread writes to a different file,
/// this measures how well the filesystem handles parallel write streams
/// without file-level lock contention.
fn bench_concurrent_write(c: &mut Criterion) {
    let mut group = c.benchmark_group("concurrent_write");
    group.sample_size(10);

    let records_per_thread = 1_000_000u64;

    for n_threads in [2, 4, 8] {
        let total = records_per_thread * n_threads as u64;
        group.throughput(Throughput::Elements(total));
        group.bench_with_input(
            BenchmarkId::new("threads", n_threads),
            &n_threads,
            |b, &n_threads| {
                b.iter(|| {
                    concurrent_writes(n_threads, records_per_thread);
                });
            },
        );
    }
    group.finish();
}

// ---------------------------------------------------------------------------
// Streaming / callback-mode benchmarks
// ---------------------------------------------------------------------------

/// Measure batched-iteration throughput via `SlabReader::batch_iter`.
///
/// The file is pre-built with `count` records. Each iteration opens a
/// fresh reader, converts it to a `SlabBatchIter` with the given
/// `batch_size`, and drains all batches. Throughput is records per second.
fn bench_batch_iter(c: &mut Criterion) {
    let mut group = c.benchmark_group("batch_iter");
    group.sample_size(10);

    let count = 1_000_000u64;
    let (_tmp, path) = prepare_file(count);

    for batch_size in [64, 1024, 16384] {
        group.throughput(Throughput::Elements(count));
        group.bench_with_input(
            BenchmarkId::new("batch_size", batch_size),
            &batch_size,
            |b, &batch_size| {
                b.iter(|| {
                    let reader = SlabReader::open(&path).unwrap();
                    let mut iter = reader.batch_iter(batch_size);
                    let mut total = 0u64;
                    loop {
                        let batch = iter.next_batch().unwrap();
                        if batch.is_empty() {
                            break;
                        }
                        total += batch.len() as u64;
                    }
                    assert_eq!(total, count);
                });
            },
        );
    }
    group.finish();
}

/// Measure synchronous sink-read throughput via `read_all_to_sink`.
///
/// Reads all records from a pre-built file into a `Vec<u8>` sink.
/// Throughput is records per second.
fn bench_read_all_to_sink(c: &mut Criterion) {
    let mut group = c.benchmark_group("read_all_to_sink");
    group.sample_size(10);

    for count in [1_000_000u64, 10_000_000] {
        let (_tmp, path) = prepare_file(count);

        group.throughput(Throughput::Elements(count));
        group.bench_with_input(
            BenchmarkId::new("records", count),
            &count,
            |b, &_count| {
                b.iter(|| {
                    let mut reader = SlabReader::open(&path).unwrap();
                    let mut sink = Vec::new();
                    let n = reader.read_all_to_sink(&mut sink).unwrap();
                    assert!(n > 0);
                });
            },
        );
    }
    group.finish();
}

/// Measure async sink-read throughput via `read_to_sink_async`.
///
/// Spawns a background thread to read all records from a pre-built file
/// into a `Vec<u8>` sink, then waits for completion. This measures the
/// full callback-mode lifecycle: thread spawn, file open on the
/// background thread, sequential iteration with progress updates, and
/// join.
fn bench_read_to_sink_async(c: &mut Criterion) {
    let mut group = c.benchmark_group("read_to_sink_async");
    group.sample_size(10);

    for count in [1_000_000u64, 10_000_000] {
        let (_tmp, path) = prepare_file(count);

        group.throughput(Throughput::Elements(count));
        group.bench_with_input(
            BenchmarkId::new("records", count),
            &count,
            |b, &_count| {
                b.iter(|| {
                    let sink: Vec<u8> = Vec::new();
                    let task = SlabReader::read_to_sink_async(
                        path.clone(),
                        sink,
                        |_| {},
                    );
                    let n = task.wait().unwrap();
                    assert!(n > 0);
                });
            },
        );
    }
    group.finish();
}

/// Measure async iterator-write throughput via `write_from_iter_async`.
///
/// Spawns a background thread that consumes an iterator of `count`
/// records and writes them to a fresh slab file. Measures the full
/// callback-mode write lifecycle including thread spawn, file creation,
/// record iteration with progress updates, finish, and join.
fn bench_write_from_iter_async(c: &mut Criterion) {
    let mut group = c.benchmark_group("write_from_iter_async");
    group.sample_size(10);

    for count in [1_000_000u64, 10_000_000] {
        group.throughput(Throughput::Elements(count));
        group.bench_with_input(
            BenchmarkId::new("records", count),
            &count,
            |b, &count| {
                b.iter(|| {
                    let tmp = NamedTempFile::new().unwrap();
                    let path = tmp.path().to_path_buf();
                    let iter = (0..count).map(make_record);
                    let task = SlabWriter::write_from_iter_async(
                        path,
                        WriterConfig::default(),
                        iter,
                        |_| {},
                    );
                    let n = task.wait().unwrap();
                    assert_eq!(n, count);
                });
            },
        );
    }
    group.finish();
}

/// Measure bulk-write throughput via `add_records`.
///
/// Pre-generates all records, then writes them in a single
/// `add_records` call. Contrasts with the single-record `bench_write`
/// to show the overhead (or lack thereof) of the bulk API.
fn bench_bulk_write(c: &mut Criterion) {
    let mut group = c.benchmark_group("bulk_write");
    group.sample_size(10);

    for count in [1_000_000u64] {
        let records: Vec<Vec<u8>> = (0..count).map(make_record).collect();
        let refs: Vec<&[u8]> = records.iter().map(|r| r.as_slice()).collect();

        group.throughput(Throughput::Elements(count));
        group.bench_with_input(
            BenchmarkId::new("records", count),
            &count,
            |b, &_count| {
                b.iter(|| {
                    let tmp = NamedTempFile::new().unwrap();
                    let path = tmp.path().to_path_buf();
                    let mut writer = SlabWriter::new(&path, WriterConfig::default()).unwrap();
                    writer.add_records(&refs).unwrap();
                    writer.finish().unwrap();
                });
            },
        );
    }
    group.finish();
}

criterion_group!(
    benches,
    bench_write,
    bench_sequential_read,
    bench_random_read,
    bench_concurrent_random_read,
    bench_concurrent_sequential_read,
    bench_concurrent_write,
    bench_batch_iter,
    bench_read_all_to_sink,
    bench_read_to_sink_async,
    bench_write_from_iter_async,
    bench_bulk_write,
);
criterion_main!(benches);
